### ISSUE TITLE
Implement immediately decidable property

### ISSUE THREAD

**Issue by tkmct** [cryptoeconomicslab/wakkanay#116]
decider should return another property if it's immediately decidable.

**Comment by syuhei176** [comment]
### Client logic

here is client logic to challenge.

exit property is `VerifyInclusion(su, inclusionProof) and ¬su() and checkpoint(su)`

1. client(let say A) handles an exit attempt by someone(let say B).
2. If the exit claim is decided and the result is false, A can challenge.
3. The decision includes `challenges` to call "challenge" method on UAC.  The client A calls `UAC.challenge(exit, challenges, challengeProperty)`

4-a. if `challengeProperty` is "immediately decidable", A decides that `su()` is true in client.
* challenges are `[[1, "¬¬su()"], [∅, "¬su()"], [∅, "su()"]]`
* challengeProperty is `su()`

A should get witness list from the decision to call `decideTrue` on StateUpdate contract.

4-b. if `challengeProperty` isn't "immediately decidable", A claim `¬old_su()` to UAC.

* challenges are `[[2, "¬checkpoint()"], [∅, "checkpoint()"], [b, "¬checkpointFF(b, c)"], [∅, "checkpointFF(b, c)"], [old_su, "¬old_su()"]]`
* challengeProperty is `¬old_su()`

**Comment by syuhei176** [comment]
I made simple rules for that.
https://github.com/cryptoeconomicslab/ovm-compiler/issues/10#issuecomment-564841915
