### ISSUE TITLE
Implement Tezos adaptor

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/wakkanay#13]
Implement L1 adaptor for Tezos. It must cover EventWatcher, contractWrapper and key management.

- [x] Wallet
- [ ] EventWatcher
- [ ] Coder
- [ ] CommitmentContractWrapper
- [ ] DepositContractWrapper
- [ ] UAContractWrapper

**Comment by daiki44** [comment]
We should also think about the log's interface @shogochiai

**Comment by daiki44** [comment]
@shogochiai 
At first, we should design how to do it. Do you have any idea?

**Comment by shogochiai** [comment]
@daiki44 

## EventWatcher
I made a sample of logging method
[ovm.tz deposit.ligo](https://github.com/cryptoeconomicslab/ovm.tz/blob/master/contracts/actions/deposit.ligo#L53)
I have to check how to read data from Tezos in order to consolidate polling interface.

**Comment by daiki44** [comment]
Can invocate a Tezos contract using this method.
https://github.com/Cryptonomic/ConseilJS/blob/master/src/chain/tezos/TezosNodeWriter.ts#L445

**Comment by daiki44** [comment]
moved to https://github.com/cryptoeconomicslab/wakkanay-tezos
