### ISSUE TITLE
Couldn't call wakkanay/types from NodeJS

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/wakkanay#172]
# Purpose
To use `types.BigNumber.toString()` in the ovm.tz's NodeJS test.

# Problem
`ReferenceError: BigInt is not defined` has been occured.

# Analysis
Typescript is not built on the repository and wakkanay npm package hasn't been published yet, and so I cannot use the Codable object in the NodeJS project.

# Solution
npm package and built dir will be shared in near future and the usage of BigNumber object is not mandatory for me, so I just wait until it will be published.

**Comment by tkmct** [comment]
What is your node.js version?
you should use greater than v10

**Comment by tkmct** [comment]
http://thecodebarbarian.com/an-overview-of-bigint-in-node-js.html
