### ISSUE TITLE
DoubleLayerTree order of AddressTreeLeaves

### ISSUE THREAD

**Issue by Ybrin** [cryptoeconomicslab/wakkanay#216]
I just stumbled upon the constructor of the DoubleLayerTree in wakkanay and I think I found a potential issue.

https://github.com/cryptoeconomicslab/wakkanay/blob/master/packages/merkle-tree/src/DoubleLayerTree.ts#L115-L126

[RFC7159](http://www.rfc-editor.org/rfc/rfc7159.txt) doesn't say anything about the order of objects. So it's an implementation detail whether the order is preserved or not.    
As far as it comes to JS I found the following articles: [1] and [2].

To sum it up, the order is preserved, but in a different way than just simple FIFO like an array.

The issue in the code I linked above is that we assume the order to be like in a FIFO array. We use the map later to iterate over all entries and generate the AddressTree leaves, which have to be in the correct order.

I do it a little bit different in Kushiro (see [here]).    
I use an array of tuples (in JS really objects with two fields) and iterate over them.

As far as the tests go the current implementation is stable. But assuming we want to support multiple nodejs Versions or totally other Javascript runtimes, it would be a safer solution to go with an array which will always be in the correct order instead of the rather unstable Map option.

CC: @syuhei176 @tkmct 

[1]: https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order
[2]: https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/
[here]: https://github.com/cryptoeconomicslab/Kushiro/blob/feature/january/Sources/Kushiro/Core/MerkleTree/DoubleLayerTree.swift#L103-L119

**Comment by syuhei176** [comment]
@Ybrin Thank you for your investigation and suggestions! I was able to understand the problem.

I think tree generation function must throw an exception when getting invalid order leaves.
And IntervalTree has that.
https://github.com/cryptoeconomicslab/wakkanay/blob/master/packages/merkle-tree/src/IntervalTree.ts#L110

So we need same restriction [here](https://github.com/cryptoeconomicslab/wakkanay/blob/master/packages/merkle-tree/src/AddressTree.ts#L81). I'll check that this solution is correct or not by writing unit test.
