### ISSUE TITLE
Modify Property data structure?

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/wakkanay#41]
related to https://github.com/cryptoeconomicslab/ovm-contracts/issues/30

```
export class Property {
  public deciderAddress: Address
  public inputs: Bytes[]
  public properties: Bytes[]
}
```

### Why modification required?

To replace variables easily.
https://github.com/cryptoeconomicslab/ovm-contracts/pull/27/files#diff-08cb96090d3e22a5a2ce227908abd4b2R44-R53

**Comment by tkmct** [comment]
@syuhei176 can I close this?

**Comment by syuhei176** [comment]
yes, but I wanna continue the discussion in https://github.com/cryptoeconomicslab/ovm-contracts/issues/30.
