### ISSUE TITLE
Build and publish to npm

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/wakkanay#56]
build and publish to npm because some Interfaces can be used in ovm-contract.

**Comment by tkmct** [comment]
actually, we can use git repo as npm package.
https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly.
so we don't need to publish for now.

**Comment by syuhei176** [comment]
We will build source files before publishing instead of before committing, so built files not in the Git repo. So we can't install package from this git repo now, right?
