### ISSUE TITLE
Implement network layer

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/wakkanay#7]
## Description

- pubsub client
- pubsub server

check the interface https://github.com/libp2p/js-libp2p-pubsub

**Comment by syuhei176** [comment]
## Why we need pubsub?

We need
- "Request-response" model for regular plasma transfer and history verifycation
- "point to point" model for Instant finality 

Pubsub can cover both.

## Why we use socket.io for the first implementation

Where are no standards protocol of pubsub for layer2. We should define universal interface as possible, but replace message format in future.

**Comment by tkmct** [comment]
I think following this spec is safe for now.
https://github.com/libp2p/specs/tree/master/pubsub

**Comment by syuhei176** [comment]
I wanna follow this but it seems too big for now.
And if we use some pubsub library, it may include some specs of this libp2p message format(e.g. topicIds).

**Comment by syuhei176** [comment]
Define the interface for "pubsub server", this interface is same as client interface but implementation should be server. Because we wanna build aggregator as client but actually it would be server. is it possible?
